# Site settings
title: Z's blog
url: "https://zheng-shen.github.io"
baseurl: ""

# Build settings
markdown: kramdown

# Keep non-Jekyll files (Gemfile etc.) out of the published site, if you add any
exclude:
  - README.md
