# Site settings
title: Z's blog
description: >- # this means to ignore newlines until "baseurl:"
  Z's personal website
baseurl: "https://zheng-shen.github.io/blog" # the subpath of your site, e.g. /blog — leave empty if none
url: "https://zheng-shen.github.io/" # the base hostname & protocol, e.g. https://yourusername.github.io

# Build settings
markdown: kramdown
theme: minima # remove this line if you're writing your own layouts instead

# Optional: shows up in minima's footer/header if you use that theme
author: Z
# github_username: yourusername

# Exclude files from being processed/published by Jekyll
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
